import { useMemo } from "react";
import type { VolcanoItem } from "../types";

// Curated list of currently/recently active volcanoes (2024-2026)
const ACTIVE_VOLCANOES: VolcanoItem[] = [
  {
    id: "v-kilauea",
    lat: 19.421,
    lng: -155.287,
    name: "Kīlauea",
    country: "USA (Hawaii)",
    status: "Erupting",
    title: "Kīlauea — Erupting (Hawaii, USA)",
    isVolcano: true,
  },
  {
    id: "v-mauna-loa",
    lat: 19.475,
    lng: -155.608,
    name: "Mauna Loa",
    country: "USA (Hawaii)",
    status: "Active",
    title: "Mauna Loa — Active (Hawaii, USA)",
    isVolcano: true,
  },
  {
    id: "v-etna",
    lat: 37.748,
    lng: 14.999,
    name: "Etna",
    country: "Italy",
    status: "Erupting",
    title: "Etna — Erupting (Sicily, Italy)",
    isVolcano: true,
  },
  {
    id: "v-stromboli",
    lat: 38.789,
    lng: 15.213,
    name: "Stromboli",
    country: "Italy",
    status: "Erupting",
    title: "Stromboli — Continuously Erupting (Italy)",
    isVolcano: true,
  },
  {
    id: "v-sakurajima",
    lat: 31.581,
    lng: 130.659,
    name: "Sakurajima",
    country: "Japan",
    status: "Erupting",
    title: "Sakurajima — Erupting (Japan)",
    isVolcano: true,
  },
  {
    id: "v-semeru",
    lat: -8.108,
    lng: 112.922,
    name: "Semeru",
    country: "Indonesia",
    status: "Erupting",
    title: "Semeru — Erupting (Java, Indonesia)",
    isVolcano: true,
  },
  {
    id: "v-ibu",
    lat: 1.494,
    lng: 127.632,
    name: "Ibu",
    country: "Indonesia",
    status: "Erupting",
    title: "Ibu — Erupting (Halmahera, Indonesia)",
    isVolcano: true,
  },
  {
    id: "v-lewotobi",
    lat: -8.542,
    lng: 122.775,
    name: "Lewotobi",
    country: "Indonesia",
    status: "Erupting",
    title: "Lewotobi — Erupting (Indonesia)",
    isVolcano: true,
  },
  {
    id: "v-merapi",
    lat: -7.541,
    lng: 110.446,
    name: "Merapi",
    country: "Indonesia",
    status: "Unrest",
    title: "Merapi — High Activity (Java, Indonesia)",
    isVolcano: true,
  },
  {
    id: "v-marapi",
    lat: -0.38,
    lng: 100.474,
    name: "Marapi",
    country: "Indonesia",
    status: "Erupting",
    title: "Marapi — Erupting (Sumatra, Indonesia)",
    isVolcano: true,
  },
  {
    id: "v-erebus",
    lat: -77.53,
    lng: 167.17,
    name: "Erebus",
    country: "Antarctica",
    status: "Erupting",
    title: "Erebus — Continuously Erupting (Antarctica)",
    isVolcano: true,
  },
  {
    id: "v-yasur",
    lat: -19.532,
    lng: 169.447,
    name: "Yasur",
    country: "Vanuatu",
    status: "Erupting",
    title: "Yasur — Continuously Erupting (Vanuatu)",
    isVolcano: true,
  },
  {
    id: "v-nyiragongo",
    lat: -1.52,
    lng: 29.25,
    name: "Nyiragongo",
    country: "DR Congo",
    status: "Unrest",
    title: "Nyiragongo — Unrest (DR Congo)",
    isVolcano: true,
  },
  {
    id: "v-ol-doinyo",
    lat: -2.764,
    lng: 35.914,
    name: "Ol Doinyo Lengai",
    country: "Tanzania",
    status: "Active",
    title: "Ol Doinyo Lengai — Active (Tanzania)",
    isVolcano: true,
  },
  {
    id: "v-erta-ale",
    lat: 13.6,
    lng: 40.67,
    name: "Erta Ale",
    country: "Ethiopia",
    status: "Erupting",
    title: "Erta Ale — Lava Lake Active (Ethiopia)",
    isVolcano: true,
  },
  {
    id: "v-fuego",
    lat: 14.473,
    lng: -90.88,
    name: "Fuego",
    country: "Guatemala",
    status: "Erupting",
    title: "Fuego — Erupting (Guatemala)",
    isVolcano: true,
  },
  {
    id: "v-popocatepetl",
    lat: 19.023,
    lng: -98.622,
    name: "Popocatépetl",
    country: "Mexico",
    status: "Unrest",
    title: "Popocatépetl — High Activity (Mexico)",
    isVolcano: true,
  },
  {
    id: "v-sheveluch",
    lat: 56.653,
    lng: 161.36,
    name: "Sheveluch",
    country: "Russia",
    status: "Erupting",
    title: "Sheveluch — Erupting (Kamchatka, Russia)",
    isVolcano: true,
  },
  {
    id: "v-bezymianny",
    lat: 55.972,
    lng: 160.595,
    name: "Bezymianny",
    country: "Russia",
    status: "Active",
    title: "Bezymianny — Active (Kamchatka, Russia)",
    isVolcano: true,
  },
  {
    id: "v-soufriere",
    lat: 16.712,
    lng: -62.177,
    name: "Soufrière Hills",
    country: "Montserrat",
    status: "Unrest",
    title: "Soufrière Hills — Unrest (Montserrat)",
    isVolcano: true,
  },
  {
    id: "v-piton",
    lat: -21.244,
    lng: 55.708,
    name: "Piton de la Fournaise",
    country: "Réunion (France)",
    status: "Erupting",
    title: "Piton de la Fournaise — Erupting (Réunion)",
    isVolcano: true,
  },
  {
    id: "v-home-reef",
    lat: -18.992,
    lng: -174.775,
    name: "Home Reef",
    country: "Tonga",
    status: "Erupting",
    title: "Home Reef — Submarine Eruption (Tonga)",
    isVolcano: true,
  },
  {
    id: "v-great-sitkin",
    lat: 52.076,
    lng: -176.13,
    name: "Great Sitkin",
    country: "USA (Alaska)",
    status: "Unrest",
    title: "Great Sitkin — Unrest (Aleutians, USA)",
    isVolcano: true,
  },
  {
    id: "v-kanlaon",
    lat: 10.41,
    lng: 123.13,
    name: "Kanlaon",
    country: "Philippines",
    status: "Unrest",
    title: "Kanlaon — Unrest (Philippines)",
    isVolcano: true,
  },
  {
    id: "v-bulusan",
    lat: 12.769,
    lng: 124.056,
    name: "Bulusan",
    country: "Philippines",
    status: "Unrest",
    title: "Bulusan — Unrest (Philippines)",
    isVolcano: true,
  },
];

export function useVolcanoes(): VolcanoItem[] {
  return useMemo(() => ACTIVE_VOLCANOES, []);
}
