// Country/city keyword → approximate lat/lng
// Used to geocode news stories by scanning title+description for country names
// Ordered from most-specific (city-level) to least (country-level) to avoid partial matches

export interface GeoLocation {
  precision: "city" | "country";
  lat: number;
  lng: number;
  country: string;
}

export const COUNTRY_GEO: Array<{
  keywords: string[];
  lat: number;
  lng: number;
  country: string;
  precision?: "city" | "country";
}> = [
  // ============================================================
  // CITY-LEVEL ENTRIES (more specific — matched first)
  // ============================================================

  // ====== US Cities ======
  {
    keywords: ["denver", "colorado"],
    lat: 39.7,
    lng: -104.9,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["minneapolis", "minnesota", "twin cities"],
    lat: 44.9,
    lng: -93.2,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["kansas city"],
    lat: 39.1,
    lng: -94.6,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["salt lake city", "utah"],
    lat: 40.8,
    lng: -111.9,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["new orleans", "louisiana"],
    lat: 30.0,
    lng: -90.1,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["baltimore", "maryland"],
    lat: 39.3,
    lng: -76.6,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["indianapolis", "indiana"],
    lat: 39.8,
    lng: -86.2,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["louisville", "kentucky"],
    lat: 38.3,
    lng: -85.8,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["milwaukee", "wisconsin"],
    lat: 43.0,
    lng: -87.9,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["richmond", "virginia"],
    lat: 37.5,
    lng: -77.4,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["buffalo new york", "buffalo, ny"],
    lat: 42.9,
    lng: -78.9,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["hartford", "connecticut"],
    lat: 41.8,
    lng: -72.7,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["providence", "rhode island"],
    lat: 41.8,
    lng: -71.4,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["albuquerque", "new mexico"],
    lat: 35.1,
    lng: -106.7,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["tucson"],
    lat: 32.2,
    lng: -110.9,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["el paso"],
    lat: 31.8,
    lng: -106.4,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["sacramento"],
    lat: 38.6,
    lng: -121.5,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["san diego"],
    lat: 32.7,
    lng: -117.2,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["oakland"],
    lat: 37.8,
    lng: -122.3,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["st. louis", "st louis", "saint louis"],
    lat: 38.6,
    lng: -90.2,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["oklahoma city", "oklahoma"],
    lat: 35.5,
    lng: -97.5,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["omaha", "nebraska"],
    lat: 41.3,
    lng: -96.0,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["boise", "idaho"],
    lat: 43.6,
    lng: -116.2,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["columbia south carolina"],
    lat: 34.0,
    lng: -81.0,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["jackson mississippi", "mississippi"],
    lat: 32.3,
    lng: -90.2,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["montgomery alabama", "alabama"],
    lat: 32.4,
    lng: -86.3,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["little rock", "arkansas"],
    lat: 34.7,
    lng: -92.3,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["des moines", "iowa"],
    lat: 41.6,
    lng: -93.6,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["madison wisconsin"],
    lat: 43.1,
    lng: -89.4,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["lansing michigan"],
    lat: 42.7,
    lng: -84.6,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["charleston west virginia", "west virginia"],
    lat: 38.4,
    lng: -81.6,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["cheyenne", "wyoming"],
    lat: 41.1,
    lng: -104.8,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["helena montana", "montana"],
    lat: 46.6,
    lng: -112.0,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["bismarck", "north dakota"],
    lat: 46.8,
    lng: -100.8,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["pierre south dakota", "south dakota"],
    lat: 44.4,
    lng: -100.3,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["concord new hampshire", "new hampshire"],
    lat: 43.2,
    lng: -71.5,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["montpelier vermont", "vermont"],
    lat: 44.3,
    lng: -72.6,
    country: "USA",
    precision: "city",
  },
  {
    keywords: ["augusta maine", "maine"],
    lat: 44.3,
    lng: -69.8,
    country: "USA",
    precision: "city",
  },

  // ====== Canadian Cities ======
  {
    keywords: ["calgary", "alberta"],
    lat: 51.0,
    lng: -114.1,
    country: "Canada",
    precision: "city",
  },
  {
    keywords: ["edmonton"],
    lat: 53.5,
    lng: -113.5,
    country: "Canada",
    precision: "city",
  },
  {
    keywords: ["winnipeg", "manitoba"],
    lat: 49.9,
    lng: -97.1,
    country: "Canada",
    precision: "city",
  },
  {
    keywords: ["halifax", "nova scotia"],
    lat: 44.6,
    lng: -63.6,
    country: "Canada",
    precision: "city",
  },

  // ====== Latin America Cities ======
  {
    keywords: ["medellin", "medell\u00edn"],
    lat: 6.2,
    lng: -75.6,
    country: "Colombia",
    precision: "city",
  },
  {
    keywords: ["cali colombia", "cali, colombia"],
    lat: 3.4,
    lng: -76.5,
    country: "Colombia",
    precision: "city",
  },
  {
    keywords: ["barranquilla"],
    lat: 11.0,
    lng: -74.8,
    country: "Colombia",
    precision: "city",
  },
  {
    keywords: ["cartagena colombia"],
    lat: 10.4,
    lng: -75.5,
    country: "Colombia",
    precision: "city",
  },
  {
    keywords: ["callao"],
    lat: -12.1,
    lng: -77.1,
    country: "Peru",
    precision: "city",
  },
  {
    keywords: ["arequipa"],
    lat: -16.4,
    lng: -71.5,
    country: "Peru",
    precision: "city",
  },
  {
    keywords: ["guayaquil"],
    lat: -2.2,
    lng: -79.9,
    country: "Ecuador",
    precision: "city",
  },
  {
    keywords: ["cuenca ecuador"],
    lat: -2.9,
    lng: -79.0,
    country: "Ecuador",
    precision: "city",
  },
  {
    keywords: ["recife"],
    lat: -8.1,
    lng: -34.9,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["salvador bahia", "salvador brazil"],
    lat: -12.9,
    lng: -38.5,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["porto alegre"],
    lat: -30.0,
    lng: -51.2,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["fortaleza"],
    lat: -3.7,
    lng: -38.5,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["manaus"],
    lat: -3.1,
    lng: -60.0,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["curitiba"],
    lat: -25.4,
    lng: -49.3,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["bel\u00e9m brazil", "belem brazil"],
    lat: -1.5,
    lng: -48.5,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["macei\u00f3", "maceio"],
    lat: -9.7,
    lng: -35.7,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["natal brazil"],
    lat: -5.8,
    lng: -35.2,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["campinas"],
    lat: -22.9,
    lng: -47.1,
    country: "Brazil",
    precision: "city",
  },
  {
    keywords: ["concepcion chile", "concepci\u00f3n chile"],
    lat: -36.8,
    lng: -73.1,
    country: "Chile",
    precision: "city",
  },
  {
    keywords: ["antofagasta"],
    lat: -23.7,
    lng: -70.4,
    country: "Chile",
    precision: "city",
  },
  {
    keywords: ["rosario argentina", "rosario,"],
    lat: -33.0,
    lng: -60.7,
    country: "Argentina",
    precision: "city",
  },
  {
    keywords: ["mendoza"],
    lat: -32.9,
    lng: -68.8,
    country: "Argentina",
    precision: "city",
  },
  {
    keywords: ["c\u00f3rdoba argentina", "cordoba argentina"],
    lat: -31.4,
    lng: -64.2,
    country: "Argentina",
    precision: "city",
  },
  {
    keywords: ["maracaibo"],
    lat: 10.7,
    lng: -71.6,
    country: "Venezuela",
    precision: "city",
  },
  {
    keywords: ["valencia venezuela"],
    lat: 10.2,
    lng: -68.0,
    country: "Venezuela",
    precision: "city",
  },
  {
    keywords: ["barquisimeto"],
    lat: 10.1,
    lng: -69.3,
    country: "Venezuela",
    precision: "city",
  },
  {
    keywords: ["cochabamba"],
    lat: -17.4,
    lng: -66.2,
    country: "Bolivia",
    precision: "city",
  },
  {
    keywords: ["santa cruz bolivia"],
    lat: -17.8,
    lng: -63.2,
    country: "Bolivia",
    precision: "city",
  },
  {
    keywords: ["bujumbura", "burundi"],
    lat: -3.4,
    lng: 29.4,
    country: "Burundi",
    precision: "city",
  },
  {
    keywords: ["gitega"],
    lat: -3.4,
    lng: 29.9,
    country: "Burundi",
    precision: "city",
  },
  {
    keywords: ["bangui", "central african republic", "car "],
    lat: 4.4,
    lng: 18.6,
    country: "Central African Republic",
    precision: "city",
  },
  {
    keywords: ["malabo", "equatorial guinea"],
    lat: 3.8,
    lng: 8.8,
    country: "Equatorial Guinea",
    precision: "city",
  },
  {
    keywords: ["libreville", "gabon"],
    lat: 0.4,
    lng: 9.5,
    country: "Gabon",
    precision: "city",
  },
  {
    keywords: ["sao tome", "s\u00e3o tom\u00e9"],
    lat: 0.3,
    lng: 6.7,
    country: "São Tomé",
    precision: "city",
  },
  {
    keywords: ["praia", "cape verde"],
    lat: 14.9,
    lng: -23.5,
    country: "Cape Verde",
    precision: "city",
  },
  {
    keywords: ["banjul", "gambia"],
    lat: 13.5,
    lng: -16.6,
    country: "Gambia",
    precision: "city",
  },
  {
    keywords: ["bissau", "guinea-bissau", "guinea bissau"],
    lat: 11.9,
    lng: -15.6,
    country: "Guinea-Bissau",
    precision: "city",
  },

  // ====== European Cities ======
  {
    keywords: ["marseille"],
    lat: 43.3,
    lng: 5.4,
    country: "France",
    precision: "city",
  },
  {
    keywords: ["nice france", "nice,"],
    lat: 43.7,
    lng: 7.3,
    country: "France",
    precision: "city",
  },
  {
    keywords: ["toulouse"],
    lat: 43.6,
    lng: 1.4,
    country: "France",
    precision: "city",
  },
  {
    keywords: ["strasbourg"],
    lat: 48.6,
    lng: 7.7,
    country: "France",
    precision: "city",
  },
  {
    keywords: ["bordeaux"],
    lat: 44.8,
    lng: -0.6,
    country: "France",
    precision: "city",
  },
  {
    keywords: ["munich", "m\u00fcnchen", "oktoberfest", "bavaria"],
    lat: 48.1,
    lng: 11.6,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["frankfurt"],
    lat: 50.1,
    lng: 8.7,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["cologne", "k\u00f6ln"],
    lat: 50.9,
    lng: 6.9,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["hamburg"],
    lat: 53.6,
    lng: 10.0,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["stuttgart"],
    lat: 48.8,
    lng: 9.2,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["d\u00fcsseldorf", "dusseldorf"],
    lat: 51.2,
    lng: 6.8,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["dortmund"],
    lat: 51.5,
    lng: 7.5,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["essen germany"],
    lat: 51.5,
    lng: 7.0,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["nuremberg", "n\u00fcrnberg"],
    lat: 49.5,
    lng: 11.1,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["dresden"],
    lat: 51.1,
    lng: 13.7,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["leipzig"],
    lat: 51.3,
    lng: 12.4,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["hanover", "hannover"],
    lat: 52.4,
    lng: 9.7,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["bremen"],
    lat: 53.1,
    lng: 8.8,
    country: "Germany",
    precision: "city",
  },
  {
    keywords: ["milan", "milano"],
    lat: 45.5,
    lng: 9.2,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["naples", "napoli"],
    lat: 40.8,
    lng: 14.3,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["turin", "torino"],
    lat: 45.1,
    lng: 7.7,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["florence", "firenze"],
    lat: 43.8,
    lng: 11.2,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["bologna"],
    lat: 44.5,
    lng: 11.3,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["genoa", "genova"],
    lat: 44.4,
    lng: 8.9,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["palermo"],
    lat: 38.1,
    lng: 13.4,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["venice", "venezia"],
    lat: 45.4,
    lng: 12.3,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["bari"],
    lat: 41.1,
    lng: 16.9,
    country: "Italy",
    precision: "city",
  },
  {
    keywords: ["barcelona"],
    lat: 41.4,
    lng: 2.2,
    country: "Spain",
    precision: "city",
  },
  {
    keywords: ["valencia spain", "valencia, spain"],
    lat: 39.5,
    lng: -0.4,
    country: "Spain",
    precision: "city",
  },
  {
    keywords: ["seville", "sevilla"],
    lat: 37.4,
    lng: -6.0,
    country: "Spain",
    precision: "city",
  },
  {
    keywords: ["bilbao"],
    lat: 43.3,
    lng: -2.9,
    country: "Spain",
    precision: "city",
  },
  {
    keywords: ["zaragoza"],
    lat: 41.7,
    lng: -0.9,
    country: "Spain",
    precision: "city",
  },
  {
    keywords: ["m\u00e1laga", "malaga"],
    lat: 36.7,
    lng: -4.4,
    country: "Spain",
    precision: "city",
  },
  {
    keywords: ["porto", "oporto"],
    lat: 41.1,
    lng: -8.6,
    country: "Portugal",
    precision: "city",
  },
  {
    keywords: ["rotterdam"],
    lat: 51.9,
    lng: 4.5,
    country: "Netherlands",
    precision: "city",
  },
  {
    keywords: ["utrecht"],
    lat: 52.1,
    lng: 5.1,
    country: "Netherlands",
    precision: "city",
  },
  {
    keywords: ["antwerp", "antwerpen"],
    lat: 51.2,
    lng: 4.4,
    country: "Belgium",
    precision: "city",
  },
  {
    keywords: ["ghent", "gent"],
    lat: 51.1,
    lng: 3.7,
    country: "Belgium",
    precision: "city",
  },
  {
    keywords: ["zurich", "z\u00fcrich"],
    lat: 47.4,
    lng: 8.5,
    country: "Switzerland",
    precision: "city",
  },
  {
    keywords: ["geneva", "gen\u00e8ve"],
    lat: 46.2,
    lng: 6.2,
    country: "Switzerland",
    precision: "city",
  },
  {
    keywords: ["basel"],
    lat: 47.6,
    lng: 7.6,
    country: "Switzerland",
    precision: "city",
  },
  {
    keywords: ["graz"],
    lat: 47.1,
    lng: 15.4,
    country: "Austria",
    precision: "city",
  },
  {
    keywords: ["krakow", "krak\u00f3w", "cracow"],
    lat: 50.1,
    lng: 19.9,
    country: "Poland",
    precision: "city",
  },
  {
    keywords: ["gdansk", "gda\u0144sk"],
    lat: 54.4,
    lng: 18.6,
    country: "Poland",
    precision: "city",
  },
  {
    keywords: ["wroclaw", "wroc\u0142aw"],
    lat: 51.1,
    lng: 17.0,
    country: "Poland",
    precision: "city",
  },
  {
    keywords: ["lodz", "\u0141\u00f3d\u017a"],
    lat: 51.8,
    lng: 19.5,
    country: "Poland",
    precision: "city",
  },
  {
    keywords: ["poznan", "pozna\u0144"],
    lat: 52.4,
    lng: 16.9,
    country: "Poland",
    precision: "city",
  },
  {
    keywords: ["debrecen"],
    lat: 47.5,
    lng: 21.6,
    country: "Hungary",
    precision: "city",
  },
  {
    keywords: ["brno"],
    lat: 49.2,
    lng: 16.6,
    country: "Czech Republic",
    precision: "city",
  },
  {
    keywords: ["cluj-napoca", "cluj napoca", "cluj"],
    lat: 46.8,
    lng: 23.6,
    country: "Romania",
    precision: "city",
  },
  {
    keywords: ["timisoara", "timi\u015foara"],
    lat: 45.8,
    lng: 21.2,
    country: "Romania",
    precision: "city",
  },
  {
    keywords: ["novi sad"],
    lat: 45.3,
    lng: 19.8,
    country: "Serbia",
    precision: "city",
  },
  {
    keywords: ["ni\u0161", "nis serbia"],
    lat: 43.3,
    lng: 21.9,
    country: "Serbia",
    precision: "city",
  },
  {
    keywords: ["plovdiv"],
    lat: 42.1,
    lng: 24.7,
    country: "Bulgaria",
    precision: "city",
  },
  {
    keywords: ["varna"],
    lat: 43.2,
    lng: 27.9,
    country: "Bulgaria",
    precision: "city",
  },
  {
    keywords: ["split croatia", "split,"],
    lat: 43.5,
    lng: 16.4,
    country: "Croatia",
    precision: "city",
  },
  {
    keywords: ["dubrovnik"],
    lat: 42.6,
    lng: 18.1,
    country: "Croatia",
    precision: "city",
  },
  {
    keywords: ["kosice", "ko\u0161ice"],
    lat: 48.7,
    lng: 21.2,
    country: "Slovakia",
    precision: "city",
  },
  {
    keywords: ["gothenburg", "g\u00f6teborg"],
    lat: 57.7,
    lng: 12.0,
    country: "Sweden",
    precision: "city",
  },
  {
    keywords: ["malmo", "malm\u00f6"],
    lat: 55.6,
    lng: 13.0,
    country: "Sweden",
    precision: "city",
  },
  {
    keywords: ["bergen norway"],
    lat: 60.4,
    lng: 5.3,
    country: "Norway",
    precision: "city",
  },
  {
    keywords: ["aarhus", "\u00e5rhus"],
    lat: 56.2,
    lng: 10.2,
    country: "Denmark",
    precision: "city",
  },
  {
    keywords: ["tampere"],
    lat: 61.5,
    lng: 23.8,
    country: "Finland",
    precision: "city",
  },
  {
    keywords: ["turku"],
    lat: 60.5,
    lng: 22.3,
    country: "Finland",
    precision: "city",
  },
  {
    keywords: ["cork ireland"],
    lat: 51.9,
    lng: -8.5,
    country: "Ireland",
    precision: "city",
  },
  {
    keywords: ["galway"],
    lat: 53.3,
    lng: -9.1,
    country: "Ireland",
    precision: "city",
  },
  {
    keywords: ["edinburgh"],
    lat: 55.9,
    lng: -3.2,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["glasgow"],
    lat: 55.9,
    lng: -4.3,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["birmingham uk", "birmingham, uk", "birmingham england"],
    lat: 52.5,
    lng: -1.9,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["bristol"],
    lat: 51.5,
    lng: -2.6,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["liverpool"],
    lat: 53.4,
    lng: -3.0,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["leeds"],
    lat: 53.8,
    lng: -1.5,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["sheffield"],
    lat: 53.4,
    lng: -1.5,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["newcastle upon tyne", "newcastle, england"],
    lat: 55.0,
    lng: -1.6,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["nottingham"],
    lat: 52.9,
    lng: -1.2,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["leicester"],
    lat: 52.6,
    lng: -1.1,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["coventry"],
    lat: 52.4,
    lng: -1.5,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["cardiff"],
    lat: 51.5,
    lng: -3.2,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["belfast"],
    lat: 54.6,
    lng: -5.9,
    country: "UK",
    precision: "city",
  },
  {
    keywords: ["thessaloniki"],
    lat: 40.6,
    lng: 23.0,
    country: "Greece",
    precision: "city",
  },
  {
    keywords: ["istanbul"],
    lat: 41.0,
    lng: 28.9,
    country: "Turkey",
    precision: "city",
  },
  {
    keywords: ["izmir"],
    lat: 38.4,
    lng: 27.1,
    country: "Turkey",
    precision: "city",
  },
  {
    keywords: ["antalya"],
    lat: 36.9,
    lng: 30.7,
    country: "Turkey",
    precision: "city",
  },
  {
    keywords: ["bursa"],
    lat: 40.2,
    lng: 29.1,
    country: "Turkey",
    precision: "city",
  },
  {
    keywords: ["kharkiv", "kharkov"],
    lat: 50.0,
    lng: 36.3,
    country: "Ukraine",
    precision: "city",
  },
  {
    keywords: ["lviv"],
    lat: 49.8,
    lng: 24.0,
    country: "Ukraine",
    precision: "city",
  },
  {
    keywords: ["odessa", "odesa ukraine"],
    lat: 46.5,
    lng: 30.7,
    country: "Ukraine",
    precision: "city",
  },
  {
    keywords: ["dnipro", "dnipropetrovsk"],
    lat: 48.5,
    lng: 35.0,
    country: "Ukraine",
    precision: "city",
  },
  {
    keywords: ["zaporizhzhia", "zaporizhia", "zaporizh"],
    lat: 47.8,
    lng: 35.2,
    country: "Ukraine",
    precision: "city",
  },
  {
    keywords: ["mariupol"],
    lat: 47.1,
    lng: 37.5,
    country: "Ukraine",
    precision: "city",
  },
  {
    keywords: ["st. petersburg", "saint petersburg", "leningrad"],
    lat: 59.9,
    lng: 30.3,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["novosibirsk"],
    lat: 55.0,
    lng: 82.9,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["yekaterinburg", "ekaterinburg"],
    lat: 56.8,
    lng: 60.6,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["kazan"],
    lat: 55.8,
    lng: 49.1,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["nizhny novgorod"],
    lat: 56.3,
    lng: 44.0,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["chelyabinsk"],
    lat: 55.2,
    lng: 61.4,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["samara russia"],
    lat: 53.2,
    lng: 50.2,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["omsk"],
    lat: 55.0,
    lng: 73.4,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["vladivostok"],
    lat: 43.1,
    lng: 131.9,
    country: "Russia",
    precision: "city",
  },
  {
    keywords: ["kaliningrad"],
    lat: 54.7,
    lng: 20.5,
    country: "Russia",
    precision: "city",
  },

  // ====== African Cities ======
  {
    keywords: ["lagos"],
    lat: 6.5,
    lng: 3.4,
    country: "Nigeria",
    precision: "city",
  },
  {
    keywords: ["kano"],
    lat: 12.0,
    lng: 8.5,
    country: "Nigeria",
    precision: "city",
  },
  {
    keywords: ["ibadan"],
    lat: 7.4,
    lng: 3.9,
    country: "Nigeria",
    precision: "city",
  },
  {
    keywords: ["port harcourt"],
    lat: 4.8,
    lng: 7.0,
    country: "Nigeria",
    precision: "city",
  },
  {
    keywords: ["kaduna"],
    lat: 10.5,
    lng: 7.4,
    country: "Nigeria",
    precision: "city",
  },
  {
    keywords: ["mombasa"],
    lat: -4.1,
    lng: 39.7,
    country: "Kenya",
    precision: "city",
  },
  {
    keywords: ["johannesburg", "jo'burg", "joburg"],
    lat: -26.2,
    lng: 28.0,
    country: "South Africa",
    precision: "city",
  },
  {
    keywords: ["cape town"],
    lat: -33.9,
    lng: 18.4,
    country: "South Africa",
    precision: "city",
  },
  {
    keywords: ["durban"],
    lat: -29.9,
    lng: 31.0,
    country: "South Africa",
    precision: "city",
  },
  {
    keywords: ["port elizabeth", "gqeberha"],
    lat: -33.9,
    lng: 25.6,
    country: "South Africa",
    precision: "city",
  },
  {
    keywords: ["alexandria egypt"],
    lat: 31.2,
    lng: 29.9,
    country: "Egypt",
    precision: "city",
  },
  {
    keywords: ["giza"],
    lat: 30.0,
    lng: 31.2,
    country: "Egypt",
    precision: "city",
  },
  {
    keywords: ["casablanca"],
    lat: 33.6,
    lng: -7.6,
    country: "Morocco",
    precision: "city",
  },
  {
    keywords: ["marrakech", "marrakesh"],
    lat: 31.6,
    lng: -8.0,
    country: "Morocco",
    precision: "city",
  },
  {
    keywords: ["fez", "fes morocco"],
    lat: 34.0,
    lng: -5.0,
    country: "Morocco",
    precision: "city",
  },
  {
    keywords: ["tangier"],
    lat: 35.8,
    lng: -5.8,
    country: "Morocco",
    precision: "city",
  },
  {
    keywords: ["oran"],
    lat: 35.7,
    lng: -0.6,
    country: "Algeria",
    precision: "city",
  },
  {
    keywords: ["constantine algeria"],
    lat: 36.4,
    lng: 6.6,
    country: "Algeria",
    precision: "city",
  },
  {
    keywords: ["sfax"],
    lat: 34.7,
    lng: 10.8,
    country: "Tunisia",
    precision: "city",
  },
  {
    keywords: ["benghazi"],
    lat: 32.1,
    lng: 20.1,
    country: "Libya",
    precision: "city",
  },
  {
    keywords: ["omdurman"],
    lat: 15.7,
    lng: 32.5,
    country: "Sudan",
    precision: "city",
  },
  {
    keywords: ["hargeisa"],
    lat: 9.6,
    lng: 44.1,
    country: "Somalia",
    precision: "city",
  },
  {
    keywords: ["kumasi"],
    lat: 6.7,
    lng: -1.6,
    country: "Ghana",
    precision: "city",
  },
  {
    keywords: ["yaound\u00e9", "yaounde"],
    lat: 3.9,
    lng: 11.5,
    country: "Cameroon",
    precision: "city",
  },
  {
    keywords: ["douala"],
    lat: 4.1,
    lng: 9.7,
    country: "Cameroon",
    precision: "city",
  },

  // ====== Middle East Cities ======
  {
    keywords: ["jeddah", "jidda"],
    lat: 21.5,
    lng: 39.2,
    country: "Saudi Arabia",
    precision: "city",
  },
  {
    keywords: ["mecca", "makkah"],
    lat: 21.4,
    lng: 39.8,
    country: "Saudi Arabia",
    precision: "city",
  },
  {
    keywords: ["medina", "madinah"],
    lat: 24.5,
    lng: 39.6,
    country: "Saudi Arabia",
    precision: "city",
  },
  {
    keywords: ["dammam"],
    lat: 26.4,
    lng: 50.1,
    country: "Saudi Arabia",
    precision: "city",
  },
  {
    keywords: ["dubai"],
    lat: 25.2,
    lng: 55.3,
    country: "UAE",
    precision: "city",
  },
  {
    keywords: ["sharjah"],
    lat: 25.4,
    lng: 55.4,
    country: "UAE",
    precision: "city",
  },
  {
    keywords: ["kuwait city"],
    lat: 29.4,
    lng: 47.9,
    country: "Kuwait",
    precision: "city",
  },
  {
    keywords: ["salalah"],
    lat: 17.0,
    lng: 54.1,
    country: "Oman",
    precision: "city",
  },
  {
    keywords: ["isfahan", "esfahan"],
    lat: 32.7,
    lng: 51.7,
    country: "Iran",
    precision: "city",
  },
  {
    keywords: ["shiraz"],
    lat: 29.6,
    lng: 52.5,
    country: "Iran",
    precision: "city",
  },
  {
    keywords: ["mashhad"],
    lat: 36.3,
    lng: 59.6,
    country: "Iran",
    precision: "city",
  },
  {
    keywords: ["tabriz"],
    lat: 38.1,
    lng: 46.3,
    country: "Iran",
    precision: "city",
  },
  {
    keywords: ["basra"],
    lat: 30.5,
    lng: 47.8,
    country: "Iraq",
    precision: "city",
  },
  {
    keywords: ["erbil", "irbil", "arbil"],
    lat: 36.2,
    lng: 44.0,
    country: "Iraq",
    precision: "city",
  },
  {
    keywords: ["mosul"],
    lat: 36.3,
    lng: 43.1,
    country: "Iraq",
    precision: "city",
  },
  {
    keywords: ["aleppo", "halab"],
    lat: 36.2,
    lng: 37.2,
    country: "Syria",
    precision: "city",
  },
  {
    keywords: ["homs", "hims"],
    lat: 34.7,
    lng: 36.7,
    country: "Syria",
    precision: "city",
  },
  {
    keywords: ["latakia"],
    lat: 35.5,
    lng: 35.8,
    country: "Syria",
    precision: "city",
  },
  {
    keywords: ["tripoli lebanon"],
    lat: 34.4,
    lng: 35.8,
    country: "Lebanon",
    precision: "city",
  },
  {
    keywords: ["tel aviv", "jaffa"],
    lat: 32.1,
    lng: 34.8,
    country: "Israel",
    precision: "city",
  },
  {
    keywords: ["haifa"],
    lat: 32.8,
    lng: 35.0,
    country: "Israel",
    precision: "city",
  },
  {
    keywords: ["aden"],
    lat: 12.8,
    lng: 45.0,
    country: "Yemen",
    precision: "city",
  },
  {
    keywords: ["hodeidah", "hudaydah"],
    lat: 14.8,
    lng: 43.0,
    country: "Yemen",
    precision: "city",
  },
  {
    keywords: ["zarqa"],
    lat: 32.1,
    lng: 36.1,
    country: "Jordan",
    precision: "city",
  },
  {
    keywords: ["kandahar"],
    lat: 31.6,
    lng: 65.7,
    country: "Afghanistan",
    precision: "city",
  },
  {
    keywords: ["herat"],
    lat: 34.3,
    lng: 62.2,
    country: "Afghanistan",
    precision: "city",
  },
  {
    keywords: ["karachi"],
    lat: 24.9,
    lng: 67.0,
    country: "Pakistan",
    precision: "city",
  },
  {
    keywords: ["lahore"],
    lat: 31.5,
    lng: 74.3,
    country: "Pakistan",
    precision: "city",
  },
  {
    keywords: ["peshawar"],
    lat: 34.0,
    lng: 71.6,
    country: "Pakistan",
    precision: "city",
  },
  {
    keywords: ["quetta"],
    lat: 30.2,
    lng: 67.0,
    country: "Pakistan",
    precision: "city",
  },
  {
    keywords: ["faisalabad"],
    lat: 31.4,
    lng: 73.1,
    country: "Pakistan",
    precision: "city",
  },
  {
    keywords: ["rawalpindi"],
    lat: 33.6,
    lng: 73.1,
    country: "Pakistan",
    precision: "city",
  },

  // ====== South Asian Cities ======
  {
    keywords: ["mumbai", "bombay"],
    lat: 19.1,
    lng: 72.9,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["bangalore", "bengaluru"],
    lat: 12.9,
    lng: 77.6,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["kolkata", "calcutta"],
    lat: 22.6,
    lng: 88.4,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["chennai", "madras"],
    lat: 13.1,
    lng: 80.3,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["hyderabad india", "hyderabad, india"],
    lat: 17.4,
    lng: 78.5,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["pune"],
    lat: 18.5,
    lng: 73.9,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["ahmedabad"],
    lat: 23.0,
    lng: 72.6,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["surat"],
    lat: 21.2,
    lng: 72.8,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["jaipur", "pink city india"],
    lat: 26.9,
    lng: 75.8,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["lucknow"],
    lat: 26.8,
    lng: 80.9,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["kanpur"],
    lat: 26.4,
    lng: 80.4,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["nagpur"],
    lat: 21.1,
    lng: 79.1,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["indore"],
    lat: 22.7,
    lng: 75.9,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["bhopal"],
    lat: 23.3,
    lng: 77.4,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["patna"],
    lat: 25.6,
    lng: 85.1,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["agra"],
    lat: 27.2,
    lng: 78.0,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["varanasi", "benares"],
    lat: 25.3,
    lng: 83.0,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["amritsar"],
    lat: 31.6,
    lng: 74.9,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["chandigarh"],
    lat: 30.7,
    lng: 76.8,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["kochi", "cochin"],
    lat: 10.0,
    lng: 76.3,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["thiruvananthapuram", "trivandrum"],
    lat: 8.5,
    lng: 77.0,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["guwahati"],
    lat: 26.2,
    lng: 91.7,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["bhubaneswar"],
    lat: 20.3,
    lng: 85.8,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["visakhapatnam", "vizag"],
    lat: 17.7,
    lng: 83.3,
    country: "India",
    precision: "city",
  },
  {
    keywords: ["chittagong", "chattogram"],
    lat: 22.4,
    lng: 91.8,
    country: "Bangladesh",
    precision: "city",
  },
  {
    keywords: ["kandy"],
    lat: 7.3,
    lng: 80.6,
    country: "Sri Lanka",
    precision: "city",
  },

  // ====== East Asian Cities ======
  {
    keywords: ["shanghai"],
    lat: 31.2,
    lng: 121.5,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["guangzhou", "canton china"],
    lat: 23.1,
    lng: 113.3,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["shenzhen"],
    lat: 22.5,
    lng: 114.1,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["chengdu"],
    lat: 30.7,
    lng: 104.1,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["wuhan"],
    lat: 30.6,
    lng: 114.3,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["nanjing"],
    lat: 32.1,
    lng: 118.8,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["xi'an", "xian china"],
    lat: 34.3,
    lng: 108.9,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["chongqing"],
    lat: 29.6,
    lng: 106.6,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["hangzhou"],
    lat: 30.3,
    lng: 120.2,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["tianjin"],
    lat: 39.1,
    lng: 117.2,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["shenyang"],
    lat: 41.8,
    lng: 123.4,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["harbin"],
    lat: 45.8,
    lng: 126.6,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["dalian"],
    lat: 38.9,
    lng: 121.6,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["qingdao"],
    lat: 36.1,
    lng: 120.4,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["jinan"],
    lat: 36.7,
    lng: 117.0,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["zhengzhou"],
    lat: 34.8,
    lng: 113.7,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["kunming"],
    lat: 25.0,
    lng: 102.7,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["urumqi", "\u00fcrümqi"],
    lat: 43.8,
    lng: 87.6,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["lhasa", "tibet"],
    lat: 29.7,
    lng: 91.1,
    country: "China",
    precision: "city",
  },
  {
    keywords: ["macau", "macao"],
    lat: 22.2,
    lng: 113.5,
    country: "Macau",
    precision: "city",
  },
  {
    keywords: ["osaka"],
    lat: 34.7,
    lng: 135.5,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["kyoto"],
    lat: 35.0,
    lng: 135.8,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["nagoya"],
    lat: 35.2,
    lng: 137.0,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["hiroshima"],
    lat: 34.4,
    lng: 132.5,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["fukuoka"],
    lat: 33.6,
    lng: 130.4,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["sapporo"],
    lat: 43.1,
    lng: 141.4,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["yokohama"],
    lat: 35.4,
    lng: 139.6,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["kobe"],
    lat: 34.7,
    lng: 135.2,
    country: "Japan",
    precision: "city",
  },
  {
    keywords: ["busan"],
    lat: 35.1,
    lng: 129.1,
    country: "South Korea",
    precision: "city",
  },
  {
    keywords: ["incheon"],
    lat: 37.5,
    lng: 126.6,
    country: "South Korea",
    precision: "city",
  },
  {
    keywords: ["daegu"],
    lat: 35.9,
    lng: 128.6,
    country: "South Korea",
    precision: "city",
  },
  {
    keywords: ["daejeon"],
    lat: 36.4,
    lng: 127.4,
    country: "South Korea",
    precision: "city",
  },
  {
    keywords: ["kaohsiung"],
    lat: 22.6,
    lng: 120.3,
    country: "Taiwan",
    precision: "city",
  },

  // ====== Southeast Asian Cities ======
  {
    keywords: ["chiang mai"],
    lat: 18.8,
    lng: 99.0,
    country: "Thailand",
    precision: "city",
  },
  {
    keywords: ["phuket"],
    lat: 7.9,
    lng: 98.4,
    country: "Thailand",
    precision: "city",
  },
  {
    keywords: ["ho chi minh", "saigon"],
    lat: 10.8,
    lng: 106.7,
    country: "Vietnam",
    precision: "city",
  },
  {
    keywords: ["da nang", "danang"],
    lat: 16.1,
    lng: 108.2,
    country: "Vietnam",
    precision: "city",
  },
  {
    keywords: ["hue vietnam", "hu\u1ebf"],
    lat: 16.5,
    lng: 107.6,
    country: "Vietnam",
    precision: "city",
  },
  {
    keywords: ["surabaya"],
    lat: -7.3,
    lng: 112.7,
    country: "Indonesia",
    precision: "city",
  },
  {
    keywords: ["bandung"],
    lat: -6.9,
    lng: 107.6,
    country: "Indonesia",
    precision: "city",
  },
  {
    keywords: ["medan"],
    lat: -3.6,
    lng: 98.7,
    country: "Indonesia",
    precision: "city",
  },
  {
    keywords: ["semarang"],
    lat: -7.0,
    lng: 110.4,
    country: "Indonesia",
    precision: "city",
  },
  {
    keywords: ["makassar"],
    lat: -5.1,
    lng: 119.4,
    country: "Indonesia",
    precision: "city",
  },
  {
    keywords: ["bali"],
    lat: -8.4,
    lng: 115.2,
    country: "Indonesia",
    precision: "city",
  },
  {
    keywords: ["cebu"],
    lat: 10.3,
    lng: 123.9,
    country: "Philippines",
    precision: "city",
  },
  {
    keywords: ["davao"],
    lat: 7.1,
    lng: 125.6,
    country: "Philippines",
    precision: "city",
  },
  {
    keywords: ["penang"],
    lat: 5.4,
    lng: 100.4,
    country: "Malaysia",
    precision: "city",
  },
  {
    keywords: ["johor bahru"],
    lat: 1.5,
    lng: 103.8,
    country: "Malaysia",
    precision: "city",
  },
  {
    keywords: ["siem reap", "angkor"],
    lat: 13.4,
    lng: 103.9,
    country: "Cambodia",
    precision: "city",
  },
  {
    keywords: ["yangon", "rangoon"],
    lat: 16.9,
    lng: 96.2,
    country: "Myanmar",
    precision: "city",
  },
  {
    keywords: ["mandalay"],
    lat: 22.0,
    lng: 96.1,
    country: "Myanmar",
    precision: "city",
  },

  // ====== Central Asian Cities ======
  {
    keywords: ["almaty", "alma-ata"],
    lat: 43.2,
    lng: 76.9,
    country: "Kazakhstan",
    precision: "city",
  },
  {
    keywords: ["samarkand"],
    lat: 39.7,
    lng: 66.9,
    country: "Uzbekistan",
    precision: "city",
  },

  // ====== Oceanian Cities ======
  {
    keywords: ["sydney"],
    lat: -33.9,
    lng: 151.2,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["melbourne"],
    lat: -37.8,
    lng: 145.0,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["brisbane"],
    lat: -27.5,
    lng: 153.0,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["perth australia"],
    lat: -31.9,
    lng: 115.9,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["adelaide"],
    lat: -34.9,
    lng: 138.6,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["darwin australia"],
    lat: -12.5,
    lng: 130.8,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["hobart"],
    lat: -42.9,
    lng: 147.3,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["gold coast"],
    lat: -28.0,
    lng: 153.4,
    country: "Australia",
    precision: "city",
  },
  {
    keywords: ["auckland"],
    lat: -36.9,
    lng: 174.8,
    country: "New Zealand",
    precision: "city",
  },
  {
    keywords: ["christchurch new zealand"],
    lat: -43.5,
    lng: 172.6,
    country: "New Zealand",
    precision: "city",
  },

  // ============================================================
  // COUNTRY-LEVEL ENTRIES (less specific — matched as fallback)
  // ============================================================

  // ====== Americas ======
  {
    keywords: [
      "united states",
      "u.s.",
      "u.s.a",
      "usa",
      "washington d.c",
      "washington dc",
      "white house",
      "pentagon",
      "congress",
      "senate",
      "american",
    ],
    lat: 38.9,
    lng: -77.0,
    country: "USA",
  },
  {
    keywords: ["new york", "manhattan", "brooklyn", "bronx", "queens"],
    lat: 40.7,
    lng: -74.0,
    country: "USA",
  },
  {
    keywords: [
      "los angeles",
      "california",
      "san francisco",
      "silicon valley",
      "san jose",
    ],
    lat: 34.0,
    lng: -118.2,
    country: "USA",
  },
  { keywords: ["chicago", "illinois"], lat: 41.8, lng: -87.6, country: "USA" },
  {
    keywords: ["texas", "houston", "dallas", "austin", "san antonio"],
    lat: 30.3,
    lng: -97.7,
    country: "USA",
  },
  {
    keywords: ["florida", "miami", "orlando", "tallahassee", "tampa"],
    lat: 27.9,
    lng: -81.5,
    country: "USA",
  },
  {
    keywords: ["seattle", "washington state", "portland", "oregon"],
    lat: 47.6,
    lng: -122.3,
    country: "USA",
  },
  {
    keywords: ["boston", "massachusetts", "harvard", "mit"],
    lat: 42.4,
    lng: -71.1,
    country: "USA",
  },
  { keywords: ["georgia", "atlanta"], lat: 33.7, lng: -84.4, country: "USA" },
  { keywords: ["nevada", "las vegas"], lat: 36.2, lng: -115.1, country: "USA" },
  {
    keywords: ["ohio", "columbus", "cleveland", "cincinnati"],
    lat: 40.0,
    lng: -82.9,
    country: "USA",
  },
  {
    keywords: ["pennsylvania", "philadelphia", "pittsburgh"],
    lat: 40.0,
    lng: -75.2,
    country: "USA",
  },
  { keywords: ["michigan", "detroit"], lat: 42.3, lng: -83.0, country: "USA" },
  {
    keywords: ["north carolina", "south carolina", "charlotte", "raleigh"],
    lat: 35.8,
    lng: -78.6,
    country: "USA",
  },
  {
    keywords: ["tennessee", "nashville", "memphis"],
    lat: 36.2,
    lng: -86.8,
    country: "USA",
  },
  { keywords: ["arizona", "phoenix"], lat: 33.4, lng: -112.1, country: "USA" },
  { keywords: ["alaska", "anchorage"], lat: 61.2, lng: -149.9, country: "USA" },
  { keywords: ["hawaii", "honolulu"], lat: 21.3, lng: -157.8, country: "USA" },
  { keywords: ["puerto rico"], lat: 18.2, lng: -66.6, country: "USA" },

  {
    keywords: [
      "canada",
      "ottawa",
      "toronto",
      "vancouver",
      "montreal",
      "quebec",
      "alberta",
      "ontario",
    ],
    lat: 45.4,
    lng: -75.7,
    country: "Canada",
  },
  {
    keywords: [
      "mexico",
      "mexico city",
      "guadalajara",
      "monterrey",
      "tijuana",
      "mexican",
    ],
    lat: 19.4,
    lng: -99.1,
    country: "Mexico",
  },

  {
    keywords: [
      "brazil",
      "brasilia",
      "rio de janeiro",
      "s\u00e3o paulo",
      "sao paulo",
      "belo horizonte",
      "brazilian",
    ],
    lat: -15.8,
    lng: -47.9,
    country: "Brazil",
  },
  {
    keywords: [
      "argentina",
      "buenos aires",
      "cordoba argentina",
      "rosario argentina",
    ],
    lat: -34.6,
    lng: -58.4,
    country: "Argentina",
  },
  {
    keywords: [
      "colombia",
      "bogota",
      "bogot\u00e1",
      "medellin",
      "cali colombia",
    ],
    lat: 4.7,
    lng: -74.1,
    country: "Colombia",
  },
  {
    keywords: ["chile", "santiago", "valparaiso"],
    lat: -33.5,
    lng: -70.6,
    country: "Chile",
  },
  {
    keywords: ["venezuela", "caracas", "maduro"],
    lat: 10.5,
    lng: -66.9,
    country: "Venezuela",
  },
  {
    keywords: ["peru", "lima", "peruvian"],
    lat: -12.0,
    lng: -77.0,
    country: "Peru",
  },
  {
    keywords: ["bolivia", "la paz", "sucre"],
    lat: -16.5,
    lng: -68.1,
    country: "Bolivia",
  },
  {
    keywords: ["ecuador", "quito", "guayaquil"],
    lat: -0.2,
    lng: -78.5,
    country: "Ecuador",
  },
  {
    keywords: ["uruguay", "montevideo"],
    lat: -34.9,
    lng: -56.2,
    country: "Uruguay",
  },
  {
    keywords: ["paraguay", "asuncion", "asunci\u00f3n"],
    lat: -25.3,
    lng: -57.6,
    country: "Paraguay",
  },
  {
    keywords: ["cuba", "havana", "cuban"],
    lat: 23.1,
    lng: -82.4,
    country: "Cuba",
  },
  {
    keywords: ["haiti", "port-au-prince", "haitian"],
    lat: 18.5,
    lng: -72.3,
    country: "Haiti",
  },
  {
    keywords: ["dominican republic", "santo domingo"],
    lat: 18.5,
    lng: -69.9,
    country: "Dominican Republic",
  },
  {
    keywords: ["jamaica", "kingston jamaica"],
    lat: 18.0,
    lng: -76.8,
    country: "Jamaica",
  },
  {
    keywords: ["trinidad", "tobago", "port of spain"],
    lat: 10.7,
    lng: -61.5,
    country: "Trinidad",
  },
  {
    keywords: ["guatemala", "guatemala city"],
    lat: 14.6,
    lng: -90.5,
    country: "Guatemala",
  },
  {
    keywords: ["honduras", "tegucigalpa"],
    lat: 14.1,
    lng: -87.2,
    country: "Honduras",
  },
  {
    keywords: ["el salvador", "san salvador"],
    lat: 13.7,
    lng: -89.2,
    country: "El Salvador",
  },
  {
    keywords: ["nicaragua", "managua"],
    lat: 12.1,
    lng: -86.3,
    country: "Nicaragua",
  },
  {
    keywords: ["costa rica", "san jose costa"],
    lat: 9.9,
    lng: -84.1,
    country: "Costa Rica",
  },
  {
    keywords: ["panama", "panama city"],
    lat: 9.0,
    lng: -79.5,
    country: "Panama",
  },

  // ====== Europe ======
  {
    keywords: [
      "united kingdom",
      "u.k.",
      "uk ",
      "britain",
      "british",
      "england",
      "london",
      "scotland",
      "wales",
      "westminster",
      "downing street",
      "buckingham",
    ],
    lat: 51.5,
    lng: -0.1,
    country: "UK",
  },
  {
    keywords: [
      "manchester",
      "birmingham",
      "leeds",
      "glasgow",
      "edinburgh",
      "belfast",
    ],
    lat: 53.5,
    lng: -2.2,
    country: "UK",
  },
  {
    keywords: [
      "france",
      "paris",
      "french",
      "elysee",
      "\u00e9lys\u00e9e",
      "lyon",
      "marseille",
      "macron",
    ],
    lat: 48.8,
    lng: 2.3,
    country: "France",
  },
  {
    keywords: [
      "germany",
      "berlin",
      "german",
      "bundestag",
      "bundesrat",
      "munich",
      "hamburg",
      "frankfurt",
      "cologne",
      "stuttgart",
    ],
    lat: 52.5,
    lng: 13.4,
    country: "Germany",
  },
  {
    keywords: [
      "russia",
      "moscow",
      "kremlin",
      "russian",
      "putin",
      "siberia",
      "st petersburg",
      "saint petersburg",
    ],
    lat: 55.7,
    lng: 37.6,
    country: "Russia",
  },
  {
    keywords: [
      "ukraine",
      "kyiv",
      "kiev",
      "ukrainian",
      "zelensky",
      "zelenskyy",
      "donbas",
      "mariupol",
      "kharkiv",
      "odessa",
    ],
    lat: 50.4,
    lng: 30.5,
    country: "Ukraine",
  },
  {
    keywords: [
      "italy",
      "rome",
      "italian",
      "milan",
      "naples",
      "sicily",
      "turin",
      "venice",
    ],
    lat: 41.9,
    lng: 12.5,
    country: "Italy",
  },
  {
    keywords: [
      "spain",
      "madrid",
      "barcelona",
      "spanish",
      "seville",
      "valencia",
    ],
    lat: 40.4,
    lng: -3.7,
    country: "Spain",
  },
  {
    keywords: ["poland", "warsaw", "polish", "krakow", "gdansk"],
    lat: 52.2,
    lng: 21.0,
    country: "Poland",
  },
  {
    keywords: [
      "netherlands",
      "amsterdam",
      "dutch",
      "hague",
      "the hague",
      "rotterdam",
    ],
    lat: 52.4,
    lng: 4.9,
    country: "Netherlands",
  },
  {
    keywords: ["sweden", "stockholm", "swedish", "gothenburg"],
    lat: 59.3,
    lng: 18.1,
    country: "Sweden",
  },
  {
    keywords: ["norway", "oslo", "norwegian", "bergen"],
    lat: 59.9,
    lng: 10.7,
    country: "Norway",
  },
  {
    keywords: ["denmark", "copenhagen", "danish"],
    lat: 55.7,
    lng: 12.6,
    country: "Denmark",
  },
  {
    keywords: ["finland", "helsinki", "finnish"],
    lat: 60.2,
    lng: 24.9,
    country: "Finland",
  },
  {
    keywords: ["switzerland", "bern", "zurich", "geneva", "swiss", "davos"],
    lat: 46.9,
    lng: 7.4,
    country: "Switzerland",
  },
  {
    keywords: ["austria", "vienna", "austrian", "salzburg"],
    lat: 48.2,
    lng: 16.4,
    country: "Austria",
  },
  {
    keywords: ["belgium", "brussels", "belgian", "ghent", "antwerp"],
    lat: 50.8,
    lng: 4.4,
    country: "Belgium",
  },
  {
    keywords: ["portugal", "lisbon", "portuguese", "porto"],
    lat: 38.7,
    lng: -9.1,
    country: "Portugal",
  },
  {
    keywords: ["greece", "athens", "greek", "thessaloniki"],
    lat: 37.9,
    lng: 23.7,
    country: "Greece",
  },
  {
    keywords: ["hungary", "budapest", "hungarian", "orban"],
    lat: 47.5,
    lng: 19.0,
    country: "Hungary",
  },
  {
    keywords: ["czech republic", "czechia", "prague", "brno"],
    lat: 50.1,
    lng: 14.4,
    country: "Czech Republic",
  },
  {
    keywords: ["romania", "bucharest", "romanian", "cluj"],
    lat: 44.4,
    lng: 26.1,
    country: "Romania",
  },
  {
    keywords: ["serbia", "belgrade", "serbian", "novi sad"],
    lat: 44.8,
    lng: 20.5,
    country: "Serbia",
  },
  {
    keywords: ["turkey", "ankara", "istanbul", "turkish", "erdogan", "izmir"],
    lat: 39.9,
    lng: 32.9,
    country: "Turkey",
  },
  {
    keywords: ["bulgaria", "sofia", "bulgarian"],
    lat: 42.7,
    lng: 23.3,
    country: "Bulgaria",
  },
  {
    keywords: ["croatia", "zagreb", "croatian", "split croatia"],
    lat: 45.8,
    lng: 15.9,
    country: "Croatia",
  },
  {
    keywords: ["slovakia", "bratislava", "slovak"],
    lat: 48.1,
    lng: 17.1,
    country: "Slovakia",
  },
  {
    keywords: ["slovenia", "ljubljana", "slovenian"],
    lat: 46.1,
    lng: 14.5,
    country: "Slovenia",
  },
  {
    keywords: ["moldova", "chisinau", "moldovan"],
    lat: 47.0,
    lng: 28.8,
    country: "Moldova",
  },
  {
    keywords: ["belarus", "minsk", "belarusian", "lukashenko"],
    lat: 53.9,
    lng: 27.6,
    country: "Belarus",
  },
  {
    keywords: ["lithuania", "vilnius", "lithuanian"],
    lat: 54.7,
    lng: 25.3,
    country: "Lithuania",
  },
  {
    keywords: ["latvia", "riga", "latvian"],
    lat: 56.9,
    lng: 24.1,
    country: "Latvia",
  },
  {
    keywords: ["estonia", "tallinn", "estonian"],
    lat: 59.4,
    lng: 24.7,
    country: "Estonia",
  },
  {
    keywords: ["ireland", "dublin", "irish"],
    lat: 53.3,
    lng: -6.3,
    country: "Ireland",
  },
  {
    keywords: ["iceland", "reykjavik", "icelandic"],
    lat: 64.1,
    lng: -21.9,
    country: "Iceland",
  },
  {
    keywords: ["albania", "tirana", "albanian"],
    lat: 41.3,
    lng: 19.8,
    country: "Albania",
  },
  {
    keywords: ["north macedonia", "skopje"],
    lat: 42.0,
    lng: 21.4,
    country: "North Macedonia",
  },
  { keywords: ["kosovo", "pristina"], lat: 42.7, lng: 21.2, country: "Kosovo" },
  {
    keywords: ["bosnia", "sarajevo", "bosnian"],
    lat: 43.8,
    lng: 18.4,
    country: "Bosnia",
  },
  {
    keywords: ["montenegro", "podgorica"],
    lat: 42.4,
    lng: 19.3,
    country: "Montenegro",
  },
  {
    keywords: ["luxembourg", "luxembourg city"],
    lat: 49.6,
    lng: 6.1,
    country: "Luxembourg",
  },
  { keywords: ["malta", "valletta"], lat: 35.9, lng: 14.5, country: "Malta" },
  { keywords: ["cyprus", "nicosia"], lat: 35.2, lng: 33.4, country: "Cyprus" },
  {
    keywords: ["georgia country", "tbilisi"],
    lat: 41.7,
    lng: 44.8,
    country: "Georgia",
  },
  {
    keywords: ["armenia", "yerevan", "armenian"],
    lat: 40.2,
    lng: 44.5,
    country: "Armenia",
  },
  {
    keywords: ["azerbaijan", "baku", "azerbaijani"],
    lat: 40.4,
    lng: 49.9,
    country: "Azerbaijan",
  },

  // ====== Middle East ======
  {
    keywords: [
      "israel",
      "jerusalem",
      "tel aviv",
      "israeli",
      "netanyahu",
      "idf",
    ],
    lat: 31.8,
    lng: 35.2,
    country: "Israel",
  },
  {
    keywords: [
      "gaza",
      "hamas",
      "west bank",
      "palestine",
      "palestinian",
      "rafah",
      "ramallah",
    ],
    lat: 31.5,
    lng: 34.5,
    country: "Palestine",
  },
  {
    keywords: ["iran", "tehran", "iranian", "khamenei", "isfahan", "shiraz"],
    lat: 35.7,
    lng: 51.4,
    country: "Iran",
  },
  {
    keywords: ["iraq", "baghdad", "iraqi", "mosul", "basra", "erbil"],
    lat: 33.3,
    lng: 44.4,
    country: "Iraq",
  },
  {
    keywords: [
      "saudi arabia",
      "riyadh",
      "jeddah",
      "saudi",
      "mecca",
      "medina",
      "mbs",
    ],
    lat: 24.7,
    lng: 46.7,
    country: "Saudi Arabia",
  },
  {
    keywords: ["syria", "damascus", "syrian", "aleppo", "idlib"],
    lat: 33.5,
    lng: 36.3,
    country: "Syria",
  },
  {
    keywords: ["lebanon", "beirut", "lebanese", "hezbollah"],
    lat: 33.9,
    lng: 35.5,
    country: "Lebanon",
  },
  {
    keywords: ["yemen", "sanaa", "houthi", "aden"],
    lat: 15.4,
    lng: 44.2,
    country: "Yemen",
  },
  {
    keywords: ["jordan", "amman", "jordanian"],
    lat: 31.9,
    lng: 35.9,
    country: "Jordan",
  },
  {
    keywords: ["qatar", "doha", "qatari"],
    lat: 25.3,
    lng: 51.5,
    country: "Qatar",
  },
  {
    keywords: ["uae", "dubai", "abu dhabi", "emirates", "sharjah"],
    lat: 24.5,
    lng: 54.4,
    country: "UAE",
  },
  { keywords: ["kuwait", "kuwaiti"], lat: 29.4, lng: 47.9, country: "Kuwait" },
  { keywords: ["bahrain", "manama"], lat: 26.2, lng: 50.6, country: "Bahrain" },
  {
    keywords: ["oman", "muscat", "omani"],
    lat: 23.6,
    lng: 58.6,
    country: "Oman",
  },
  {
    keywords: ["afghanistan", "kabul", "afghan", "taliban", "kandahar"],
    lat: 34.5,
    lng: 69.2,
    country: "Afghanistan",
  },
  {
    keywords: [
      "pakistan",
      "islamabad",
      "karachi",
      "lahore",
      "pakistani",
      "peshawar",
    ],
    lat: 33.7,
    lng: 73.1,
    country: "Pakistan",
  },

  // ====== Asia ======
  {
    keywords: [
      "china",
      "beijing",
      "shanghai",
      "chinese",
      "xi jinping",
      "shenzhen",
      "chengdu",
      "guangzhou",
      "wuhan",
      "nanjing",
    ],
    lat: 39.9,
    lng: 116.4,
    country: "China",
  },
  {
    keywords: ["hong kong", "hk "],
    lat: 22.3,
    lng: 114.2,
    country: "Hong Kong",
  },
  {
    keywords: ["taiwan", "taipei", "taiwanese"],
    lat: 25.0,
    lng: 121.5,
    country: "Taiwan",
  },
  {
    keywords: [
      "japan",
      "tokyo",
      "japanese",
      "osaka",
      "kyoto",
      "hiroshima",
      "nagoya",
      "fukushima",
    ],
    lat: 35.7,
    lng: 139.7,
    country: "Japan",
  },
  {
    keywords: ["south korea", "korea", "seoul", "korean", "busan", "incheon"],
    lat: 37.5,
    lng: 126.9,
    country: "South Korea",
  },
  {
    keywords: ["north korea", "pyongyang", "kim jong", "dprk"],
    lat: 39.0,
    lng: 125.8,
    country: "North Korea",
  },
  {
    keywords: [
      "india",
      "new delhi",
      "delhi",
      "mumbai",
      "modi",
      "indian",
      "bangalore",
      "kolkata",
      "chennai",
      "hyderabad",
      "pune",
      "ahmedabad",
    ],
    lat: 28.6,
    lng: 77.2,
    country: "India",
  },
  {
    keywords: ["bangladesh", "dhaka", "bangladeshi", "chittagong"],
    lat: 23.7,
    lng: 90.4,
    country: "Bangladesh",
  },
  {
    keywords: ["myanmar", "burma", "yangon", "naypyidaw", "burmese"],
    lat: 19.7,
    lng: 96.1,
    country: "Myanmar",
  },
  {
    keywords: ["thailand", "bangkok", "thai", "chiang mai", "phuket"],
    lat: 13.8,
    lng: 100.5,
    country: "Thailand",
  },
  {
    keywords: ["vietnam", "hanoi", "ho chi minh", "vietnamese", "saigon"],
    lat: 21.0,
    lng: 105.8,
    country: "Vietnam",
  },
  {
    keywords: [
      "indonesia",
      "jakarta",
      "indonesian",
      "bali",
      "surabaya",
      "bandung",
    ],
    lat: -6.2,
    lng: 106.8,
    country: "Indonesia",
  },
  {
    keywords: [
      "philippines",
      "manila",
      "filipino",
      "mindanao",
      "cebu",
      "duterte",
      "marcos",
    ],
    lat: 14.6,
    lng: 120.9,
    country: "Philippines",
  },
  {
    keywords: ["malaysia", "kuala lumpur", "malaysian", "penang", "johor"],
    lat: 3.1,
    lng: 101.7,
    country: "Malaysia",
  },
  {
    keywords: ["singapore", "singaporean"],
    lat: 1.4,
    lng: 103.8,
    country: "Singapore",
  },
  {
    keywords: ["cambodia", "phnom penh", "cambodian"],
    lat: 11.6,
    lng: 104.9,
    country: "Cambodia",
  },
  {
    keywords: ["sri lanka", "colombo", "sri lankan"],
    lat: 6.9,
    lng: 79.9,
    country: "Sri Lanka",
  },
  {
    keywords: ["nepal", "kathmandu", "nepali"],
    lat: 27.7,
    lng: 85.3,
    country: "Nepal",
  },
  {
    keywords: ["kazakhstan", "astana", "almaty", "kazakh"],
    lat: 51.2,
    lng: 71.4,
    country: "Kazakhstan",
  },
  {
    keywords: ["uzbekistan", "tashkent", "uzbek"],
    lat: 41.3,
    lng: 69.2,
    country: "Uzbekistan",
  },
  {
    keywords: ["mongolia", "ulaanbaatar", "mongolian"],
    lat: 47.9,
    lng: 106.9,
    country: "Mongolia",
  },
  {
    keywords: ["laos", "vientiane", "laotian"],
    lat: 18.0,
    lng: 102.6,
    country: "Laos",
  },
  {
    keywords: ["timor-leste", "east timor", "dili"],
    lat: -8.6,
    lng: 125.6,
    country: "Timor-Leste",
  },
  {
    keywords: ["brunei", "bandar seri begawan"],
    lat: 4.9,
    lng: 114.9,
    country: "Brunei",
  },
  {
    keywords: ["kyrgyzstan", "bishkek"],
    lat: 42.9,
    lng: 74.6,
    country: "Kyrgyzstan",
  },
  {
    keywords: ["tajikistan", "dushanbe"],
    lat: 38.6,
    lng: 68.8,
    country: "Tajikistan",
  },
  {
    keywords: ["turkmenistan", "ashgabat"],
    lat: 37.9,
    lng: 58.4,
    country: "Turkmenistan",
  },
  { keywords: ["bhutan", "thimphu"], lat: 27.5, lng: 89.6, country: "Bhutan" },
  { keywords: ["maldives", "male"], lat: 4.2, lng: 73.5, country: "Maldives" },

  // ====== Africa ======
  {
    keywords: ["nigeria", "abuja", "lagos", "nigerian", "kano", "enugu"],
    lat: 9.1,
    lng: 7.5,
    country: "Nigeria",
  },
  {
    keywords: [
      "south africa",
      "pretoria",
      "johannesburg",
      "cape town",
      "south african",
      "durban",
      "anc",
      "ramaphosa",
    ],
    lat: -25.7,
    lng: 28.2,
    country: "South Africa",
  },
  {
    keywords: ["egypt", "cairo", "egyptian", "alexandria egypt", "luxor"],
    lat: 30.0,
    lng: 31.2,
    country: "Egypt",
  },
  {
    keywords: ["ethiopia", "addis ababa", "ethiopian", "tigray"],
    lat: 9.0,
    lng: 38.7,
    country: "Ethiopia",
  },
  {
    keywords: ["kenya", "nairobi", "kenyan", "mombasa"],
    lat: -1.3,
    lng: 36.8,
    country: "Kenya",
  },
  {
    keywords: ["tanzania", "dar es salaam", "tanzanian", "dodoma"],
    lat: -6.8,
    lng: 39.3,
    country: "Tanzania",
  },
  {
    keywords: ["ghana", "accra", "ghanaian", "kumasi"],
    lat: 5.6,
    lng: -0.2,
    country: "Ghana",
  },
  {
    keywords: ["senegal", "dakar", "senegalese"],
    lat: 14.7,
    lng: -17.4,
    country: "Senegal",
  },
  {
    keywords: ["morocco", "rabat", "casablanca", "moroccan", "marrakesh"],
    lat: 34.0,
    lng: -6.8,
    country: "Morocco",
  },
  {
    keywords: ["libya", "tripoli", "libyan", "benghazi"],
    lat: 32.9,
    lng: 13.2,
    country: "Libya",
  },
  {
    keywords: ["sudan", "khartoum", "sudanese", "port sudan", "darfur"],
    lat: 15.6,
    lng: 32.5,
    country: "Sudan",
  },
  {
    keywords: ["somalia", "mogadishu", "somali", "al-shabaab", "al shabaab"],
    lat: 2.1,
    lng: 45.3,
    country: "Somalia",
  },
  {
    keywords: ["congo", "kinshasa", "drc", "democratic republic of the congo"],
    lat: -4.3,
    lng: 15.3,
    country: "DR Congo",
  },
  {
    keywords: ["republic of congo", "brazzaville"],
    lat: -4.3,
    lng: 15.3,
    country: "Congo",
  },
  {
    keywords: ["mali", "bamako", "malian"],
    lat: 12.6,
    lng: -8.0,
    country: "Mali",
  },
  {
    keywords: ["zimbabwe", "harare", "zimbabwean"],
    lat: -17.8,
    lng: 31.1,
    country: "Zimbabwe",
  },
  {
    keywords: ["mozambique", "maputo", "mozambican"],
    lat: -25.9,
    lng: 32.6,
    country: "Mozambique",
  },
  {
    keywords: ["angola", "luanda", "angolan"],
    lat: -8.8,
    lng: 13.2,
    country: "Angola",
  },
  {
    keywords: ["cameroon", "yaounde", "douala"],
    lat: 3.9,
    lng: 11.5,
    country: "Cameroon",
  },
  {
    keywords: ["ivory coast", "c\u00f4te d'ivoire", "abidjan"],
    lat: 5.4,
    lng: -4.0,
    country: "Ivory Coast",
  },
  {
    keywords: ["algeria", "algiers", "algerian", "oran"],
    lat: 36.7,
    lng: 3.2,
    country: "Algeria",
  },
  {
    keywords: ["tunisia", "tunis", "tunisian"],
    lat: 36.8,
    lng: 10.2,
    country: "Tunisia",
  },
  {
    keywords: ["uganda", "kampala", "ugandan"],
    lat: 0.3,
    lng: 32.6,
    country: "Uganda",
  },
  {
    keywords: ["rwanda", "kigali", "rwandan"],
    lat: -1.9,
    lng: 30.1,
    country: "Rwanda",
  },
  {
    keywords: ["burkina faso", "ouagadougou"],
    lat: 12.4,
    lng: -1.5,
    country: "Burkina Faso",
  },
  {
    keywords: ["niger republic", "niamey"],
    lat: 13.5,
    lng: 2.1,
    country: "Niger",
  },
  {
    keywords: ["chad", "n'djamena", "chadian"],
    lat: 12.1,
    lng: 15.0,
    country: "Chad",
  },
  { keywords: ["eritrea", "asmara"], lat: 15.3, lng: 38.9, country: "Eritrea" },
  { keywords: ["djibouti"], lat: 11.6, lng: 43.1, country: "Djibouti" },
  {
    keywords: ["south sudan", "juba"],
    lat: 4.9,
    lng: 31.6,
    country: "South Sudan",
  },
  {
    keywords: ["zambia", "lusaka", "zambian"],
    lat: -15.4,
    lng: 28.3,
    country: "Zambia",
  },
  {
    keywords: ["malawi", "lilongwe", "blantyre"],
    lat: -14.0,
    lng: 33.8,
    country: "Malawi",
  },
  {
    keywords: ["namibia", "windhoek", "namibian"],
    lat: -22.6,
    lng: 17.1,
    country: "Namibia",
  },
  {
    keywords: ["botswana", "gaborone"],
    lat: -24.7,
    lng: 25.9,
    country: "Botswana",
  },
  {
    keywords: ["madagascar", "antananarivo"],
    lat: -18.9,
    lng: 47.5,
    country: "Madagascar",
  },
  {
    keywords: ["mauritius", "port louis"],
    lat: -20.2,
    lng: 57.5,
    country: "Mauritius",
  },
  { keywords: ["guinea", "conakry"], lat: 9.5, lng: -13.7, country: "Guinea" },
  {
    keywords: ["sierra leone", "freetown"],
    lat: 8.5,
    lng: -13.2,
    country: "Sierra Leone",
  },
  {
    keywords: ["liberia", "monrovia"],
    lat: 6.3,
    lng: -10.8,
    country: "Liberia",
  },
  { keywords: ["togo", "lome"], lat: 6.1, lng: 1.2, country: "Togo" },
  {
    keywords: ["benin", "porto novo", "cotonou"],
    lat: 6.4,
    lng: 2.4,
    country: "Benin",
  },
  {
    keywords: ["mauritania", "nouakchott"],
    lat: 18.1,
    lng: -15.9,
    country: "Mauritania",
  },
  {
    keywords: ["western sahara"],
    lat: 24.2,
    lng: -12.9,
    country: "Western Sahara",
  },
  {
    keywords: ["eswatini", "swaziland", "mbabane"],
    lat: -26.3,
    lng: 31.1,
    country: "Eswatini",
  },
  {
    keywords: ["lesotho", "maseru"],
    lat: -29.3,
    lng: 27.5,
    country: "Lesotho",
  },

  // ====== Oceania ======
  {
    keywords: [
      "australia",
      "canberra",
      "sydney",
      "melbourne",
      "australian",
      "brisbane",
      "perth",
      "adelaide",
    ],
    lat: -35.3,
    lng: 149.1,
    country: "Australia",
  },
  {
    keywords: [
      "new zealand",
      "wellington",
      "auckland",
      "kiwi",
      "christchurch",
      "dunedin",
    ],
    lat: -41.3,
    lng: 174.8,
    country: "New Zealand",
  },
  {
    keywords: ["papua new guinea", "port moresby"],
    lat: -9.4,
    lng: 147.2,
    country: "Papua New Guinea",
  },
  {
    keywords: ["fiji", "suva", "fijian"],
    lat: -18.1,
    lng: 178.4,
    country: "Fiji",
  },
  {
    keywords: ["solomon islands", "honiara"],
    lat: -9.4,
    lng: 160.0,
    country: "Solomon Islands",
  },
  {
    keywords: ["vanuatu", "port vila"],
    lat: -17.7,
    lng: 168.3,
    country: "Vanuatu",
  },
  { keywords: ["samoa", "apia"], lat: -13.8, lng: -172.1, country: "Samoa" },
  {
    keywords: ["tonga", "nukualofa"],
    lat: -21.1,
    lng: -175.2,
    country: "Tonga",
  },

  // ====== International / Organizations ======
  {
    keywords: [
      "united nations",
      "un ",
      "nato",
      "g7",
      "g20",
      "imf",
      "world bank",
      "wto",
      "who ",
      "eu ",
      "european union",
      "icc",
      "icj",
      "opec",
    ],
    lat: 40.7,
    lng: -74.0,
    country: "International",
  },
  {
    keywords: ["arctic", "north pole", "greenland"],
    lat: 72.0,
    lng: -40.0,
    country: "Arctic",
  },
  {
    keywords: ["antarctica", "south pole"],
    lat: -82.0,
    lng: 0.0,
    country: "Antarctica",
  },
];

/**
 * Scan text for country/city keywords and return the best GeoLocation match.
 * City-level entries appear first in the array and match before country-level fallbacks.
 * Returns null if no match found.
 */
export function geocodeText(text: string): GeoLocation | null {
  const lower = text.toLowerCase();
  // Iterate in order — city entries first, country entries last
  for (const entry of COUNTRY_GEO) {
    for (const kw of entry.keywords) {
      if (lower.includes(kw)) {
        return {
          lat: entry.lat,
          lng: entry.lng,
          country: entry.country,
          precision: entry.precision ?? "country",
        };
      }
    }
  }
  return null;
}
