/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsItem = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'fetchStooqCSV' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCachedDow' : IDL.Func([], [IDL.Text], ['query']),
  'getCachedNASDAQ' : IDL.Func([], [IDL.Text], ['query']),
  'getCachedOil' : IDL.Func([], [IDL.Text], ['query']),
  'getCachedSP500' : IDL.Func([], [IDL.Text], ['query']),
  'getLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
  'getMarketLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
  'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getNextCountry' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'refreshMarketData' : IDL.Func([], [], []),
  'refreshNews' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsItem = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'fetchStooqCSV' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCachedDow' : IDL.Func([], [IDL.Text], ['query']),
    'getCachedNASDAQ' : IDL.Func([], [IDL.Text], ['query']),
    'getCachedOil' : IDL.Func([], [IDL.Text], ['query']),
    'getCachedSP500' : IDL.Func([], [IDL.Text], ['query']),
    'getLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
    'getMarketLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
    'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getNextCountry' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'refreshMarketData' : IDL.Func([], [], []),
    'refreshNews' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };